/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: geobuf.proto */

#ifndef PROTOBUF_C_geobuf_2eproto__INCLUDED
#define PROTOBUF_C_geobuf_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Geobuf__Data Geobuf__Data;
typedef struct Geobuf__Data__Feature Geobuf__Data__Feature;
typedef struct Geobuf__Data__Geometry Geobuf__Data__Geometry;
typedef struct Geobuf__Data__FeatureCollection Geobuf__Data__FeatureCollection;
typedef struct Geobuf__Data__Value Geobuf__Data__Value;


/* --- enums --- */

typedef enum _Geobuf__Data__Geometry__Type {
  GEOBUF__DATA__GEOMETRY__TYPE__POINT = 0,
  GEOBUF__DATA__GEOMETRY__TYPE__MULTIPOINT = 1,
  GEOBUF__DATA__GEOMETRY__TYPE__LINESTRING = 2,
  GEOBUF__DATA__GEOMETRY__TYPE__MULTILINESTRING = 3,
  GEOBUF__DATA__GEOMETRY__TYPE__POLYGON = 4,
  GEOBUF__DATA__GEOMETRY__TYPE__MULTIPOLYGON = 5,
  GEOBUF__DATA__GEOMETRY__TYPE__GEOMETRYCOLLECTION = 6
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(GEOBUF__DATA__GEOMETRY__TYPE)
} Geobuf__Data__Geometry__Type;

/* --- messages --- */

typedef enum {
  GEOBUF__DATA__FEATURE__ID_TYPE__NOT_SET = 0,
  GEOBUF__DATA__FEATURE__ID_TYPE_ID = 11,
  GEOBUF__DATA__FEATURE__ID_TYPE_INT_ID = 12
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(GEOBUF__DATA__FEATURE__ID_TYPE__CASE)
} Geobuf__Data__Feature__IdTypeCase;

struct  Geobuf__Data__Feature
{
  ProtobufCMessage base;
  Geobuf__Data__Geometry *geometry;
  /*
   * unique values
   */
  size_t n_values;
  Geobuf__Data__Value **values;
  /*
   * pairs of key/value indexes
   */
  size_t n_properties;
  uint32_t *properties;
  /*
   * arbitrary properties
   */
  size_t n_custom_properties;
  uint32_t *custom_properties;
  Geobuf__Data__Feature__IdTypeCase id_type_case;
  union {
    char *id;
    int64_t int_id;
  };
};
#define GEOBUF__DATA__FEATURE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&geobuf__data__feature__descriptor) \
    , NULL, 0,NULL, 0,NULL, 0,NULL, GEOBUF__DATA__FEATURE__ID_TYPE__NOT_SET, {0} }


struct  Geobuf__Data__Geometry
{
  ProtobufCMessage base;
  Geobuf__Data__Geometry__Type type;
  /*
   * coordinate structure in lengths
   */
  size_t n_lengths;
  uint32_t *lengths;
  /*
   * delta-encoded integer values
   */
  size_t n_coords;
  int64_t *coords;
  size_t n_geometries;
  Geobuf__Data__Geometry **geometries;
  size_t n_values;
  Geobuf__Data__Value **values;
  size_t n_custom_properties;
  uint32_t *custom_properties;
};
#define GEOBUF__DATA__GEOMETRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&geobuf__data__geometry__descriptor) \
    , GEOBUF__DATA__GEOMETRY__TYPE__POINT, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL }


struct  Geobuf__Data__FeatureCollection
{
  ProtobufCMessage base;
  size_t n_features;
  Geobuf__Data__Feature **features;
  size_t n_values;
  Geobuf__Data__Value **values;
  size_t n_custom_properties;
  uint32_t *custom_properties;
};
#define GEOBUF__DATA__FEATURE_COLLECTION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&geobuf__data__feature_collection__descriptor) \
    , 0,NULL, 0,NULL, 0,NULL }


typedef enum {
  GEOBUF__DATA__VALUE__VALUE_TYPE__NOT_SET = 0,
  GEOBUF__DATA__VALUE__VALUE_TYPE_STRING_VALUE = 1,
  GEOBUF__DATA__VALUE__VALUE_TYPE_DOUBLE_VALUE = 2,
  GEOBUF__DATA__VALUE__VALUE_TYPE_POS_INT_VALUE = 3,
  GEOBUF__DATA__VALUE__VALUE_TYPE_NEG_INT_VALUE = 4,
  GEOBUF__DATA__VALUE__VALUE_TYPE_BOOL_VALUE = 5,
  GEOBUF__DATA__VALUE__VALUE_TYPE_JSON_VALUE = 6
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(GEOBUF__DATA__VALUE__VALUE_TYPE__CASE)
} Geobuf__Data__Value__ValueTypeCase;

struct  Geobuf__Data__Value
{
  ProtobufCMessage base;
  Geobuf__Data__Value__ValueTypeCase value_type_case;
  union {
    char *string_value;
    double double_value;
    uint64_t pos_int_value;
    uint64_t neg_int_value;
    protobuf_c_boolean bool_value;
    char *json_value;
  };
};
#define GEOBUF__DATA__VALUE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&geobuf__data__value__descriptor) \
    , GEOBUF__DATA__VALUE__VALUE_TYPE__NOT_SET, {0} }


typedef enum {
  GEOBUF__DATA__DATA_TYPE__NOT_SET = 0,
  GEOBUF__DATA__DATA_TYPE_FEATURE_COLLECTION = 4,
  GEOBUF__DATA__DATA_TYPE_FEATURE = 5,
  GEOBUF__DATA__DATA_TYPE_GEOMETRY = 6
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(GEOBUF__DATA__DATA_TYPE__CASE)
} Geobuf__Data__DataTypeCase;

struct  Geobuf__Data
{
  ProtobufCMessage base;
  /*
   * global arrays of unique keys
   */
  size_t n_keys;
  char **keys;
  /*
   * max coordinate dimensions
   */
  protobuf_c_boolean has_dimensions;
  uint32_t dimensions;
  /*
   * number of digits after decimal point for coordinates
   */
  protobuf_c_boolean has_precision;
  uint32_t precision;
  Geobuf__Data__DataTypeCase data_type_case;
  union {
    Geobuf__Data__FeatureCollection *feature_collection;
    Geobuf__Data__Feature *feature;
    Geobuf__Data__Geometry *geometry;
  };
};
#define GEOBUF__DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&geobuf__data__descriptor) \
    , 0,NULL, 0, 2u, 0, 6u, GEOBUF__DATA__DATA_TYPE__NOT_SET, {0} }


/* Geobuf__Data__Feature methods */
void   geobuf__data__feature__init
                     (Geobuf__Data__Feature         *message);
/* Geobuf__Data__Geometry methods */
void   geobuf__data__geometry__init
                     (Geobuf__Data__Geometry         *message);
/* Geobuf__Data__FeatureCollection methods */
void   geobuf__data__feature_collection__init
                     (Geobuf__Data__FeatureCollection         *message);
/* Geobuf__Data__Value methods */
void   geobuf__data__value__init
                     (Geobuf__Data__Value         *message);
/* Geobuf__Data methods */
void   geobuf__data__init
                     (Geobuf__Data         *message);
size_t geobuf__data__get_packed_size
                     (const Geobuf__Data   *message);
size_t geobuf__data__pack
                     (const Geobuf__Data   *message,
                      uint8_t             *out);
size_t geobuf__data__pack_to_buffer
                     (const Geobuf__Data   *message,
                      ProtobufCBuffer     *buffer);
Geobuf__Data *
       geobuf__data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   geobuf__data__free_unpacked
                     (Geobuf__Data *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Geobuf__Data__Feature_Closure)
                 (const Geobuf__Data__Feature *message,
                  void *closure_data);
typedef void (*Geobuf__Data__Geometry_Closure)
                 (const Geobuf__Data__Geometry *message,
                  void *closure_data);
typedef void (*Geobuf__Data__FeatureCollection_Closure)
                 (const Geobuf__Data__FeatureCollection *message,
                  void *closure_data);
typedef void (*Geobuf__Data__Value_Closure)
                 (const Geobuf__Data__Value *message,
                  void *closure_data);
typedef void (*Geobuf__Data_Closure)
                 (const Geobuf__Data *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor geobuf__data__descriptor;
extern const ProtobufCMessageDescriptor geobuf__data__feature__descriptor;
extern const ProtobufCMessageDescriptor geobuf__data__geometry__descriptor;
extern const ProtobufCEnumDescriptor    geobuf__data__geometry__type__descriptor;
extern const ProtobufCMessageDescriptor geobuf__data__feature_collection__descriptor;
extern const ProtobufCMessageDescriptor geobuf__data__value__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_geobuf_2eproto__INCLUDED */
